import { z } from 'zod'

/**
 * Primitives shared by every contract.
 *
 * These are deliberately small. A shared schema earns its place when the same rule is
 * needed in three or more contracts; anything narrower belongs to the contract that owns it.
 */

/**
 * Every identifier in this system is a UUID. The values are UUIDv7 generated by the
 * application, but the wire format is just a UUID — a client has no business caring which
 * version it is, and validating the version here would break the moment we import data.
 */
export const idSchema = z.uuid()

/**
 * Present on every product record. The MVP runs a single workspace and has no isolation
 * logic, but the column and the field exist from the first day: adding them later is a
 * migration across every table plus every contract at once.
 */
export const workspaceIdSchema = z.uuid()

export const isoDateTimeSchema = z.iso.datetime({ offset: true })

/**
 * The MVP is Russian only. Widening this is a product decision, not a typo fix: it pulls in
 * per-locale content, per-locale keywords and hreflang on the public site.
 */
export const localeSchema = z.enum(['ru'])

export const slugSchema = z
  .string()
  .trim()
  .min(1)
  .max(160)
  .regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/, 'slug must be lowercase words separated by single hyphens')

/**
 * SHA-256 of the exact bytes that were approved.
 *
 * This is the load-bearing value of the whole approval model: editing approved content
 * changes the hash, which detaches the approval, which makes publication impossible. See
 * docs/SERVICE_REQUESTS.md section 5.
 */
export const contentHashSchema = z
  .string()
  .regex(/^[a-f0-9]{64}$/, 'content hash must be a lowercase hex SHA-256 digest')

export const shortTextSchema = z.string().trim().min(1).max(200)
export const mediumTextSchema = z.string().trim().min(1).max(2000)
export const longTextSchema = z.string().trim().min(1).max(50_000)

/** Free-form structured payloads that the database stores as JSON. */
export const jsonObjectSchema = z.record(z.string(), z.unknown())

export const paginationQuerySchema = z.object({
  limit: z.coerce.number().int().min(1).max(100).default(20),
  cursor: idSchema.optional(),
})

export function paginatedSchema<Item extends z.ZodTypeAny>(item: Item) {
  return z.object({
    items: z.array(item),
    nextCursor: idSchema.nullable(),
  })
}

/** Audit stamps carried by most records. */
export const timestampsSchema = z.object({
  createdAt: isoDateTimeSchema,
  updatedAt: isoDateTimeSchema,
})

export type Id = z.infer<typeof idSchema>
export type Locale = z.infer<typeof localeSchema>
export type ContentHash = z.infer<typeof contentHashSchema>
export type PaginationQuery = z.infer<typeof paginationQuerySchema>
